apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: dotnet-auto
  namespace: observability
spec:
  exporter:
    endpoint: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  dotnet:
    image: <ACR_LOGIN_SERVER>/opentelemetry/autoinstrumentation-dotnet:1.15.0
    env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: grpc
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_DOTNET_AUTO_LOGS_ENABLED
        value: "true"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: deployment.environment.name=dev
      - name: OTEL_EXPORTER_OTLP_HEADERS
        valueFrom:
          secretKeyRef:
            name: otel-exporter-secret
            key: otlp_headers
