{
 "title": "Azure / Insights / Applications - Overview",
 "description": "The dashboard provides insights of Azure Apps via different metrics for app monitoring through Application Insights.",
 "tags": [ "Azure-managed" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "am_ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "ns", "label": "Namespace", "query": "microsoft.insights/components" },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "res",
    "label": "Resource",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Azure Portal Links", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "<a style=\"color: inherit;\" href=\"https://portal.azure.com/#@${tenant}/resource/subscriptions/${sub}/resourceGroups/${rg}/providers/microsoft.insights/components/${res}/overview\" target=\"_blank\">\n  <div>\n    <h3 style=\"color: #a16feb\"> ${res} </h1>\n    <h5 style=\"margin-bottom: 0px;\"> Application Insights  </h5>\n  </div>\n</a>"
   }
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "availabilityResults/availabilityPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "options": {
    "content": "<a style=\"color: inherit;\" href=\"https://portal.azure.com/#blade/AppInsightsExtension/ProactiveDetectionFeedBlade/ComponentId/%7B%22Name%22%3A%22${res}%22%2C%22SubscriptionId%22%3A%22${sub}%22%2C%22ResourceGroup%22%3A%22${rg}%22%7D/TimeContext/%7B%22durationMs%22%3A604800000%2C%22endTime%22%3Anull%2C%22createdTime%22%3A%222021-10-18T19%3A26%3A58.876Z%22%2C%22isInitialTime%22%3Atrue%2C%22grain%22%3A1%2C%22useDashboardTimeRange%22%3Afalse%7D\" target=\"_blank\">\n<div style=\"padding-top: 20px\">\n  <center><p style=\"color: #4d99b8; font-size:18px;\">Smart detection</p></center>\n  <center><p style=\"margin-top:0px;\">${res}</p></center>\n</div>\n</a>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "options": {
    "content": "<a style=\"color: inherit;\" href=\"https://portal.azure.com/#@${tenant}/resource/subscriptions/${sub}/resourceGroups/${rg}/providers/microsoft.insights/components/${res}/quickPulse\" target=\"_blank\">\n<div style=\"padding-top: 20px\">\n  <center><p style=\"color: #2272b9; font-size:18px;\">Live Metrics</p></center>\n  <center><p style=\"margin-top:0px;\">${res}</p></center>\n</div>\n</a>\n           \n           "
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "options": {
    "content": "<a style=\"color: inherit;\" href=\"https://portal.azure.com/#@${tenant}/resource/subscriptions/${sub}/resourceGroups/${rg}/providers/microsoft.insights/components/${res}/applicationMap\" target=\"_blank\">\n<div style=\"padding-top: 20px;\">\n  <center><p style=\"position:center; color: #ff8c00; font-size:18px\">App map</p></center>\n  <center><p style=\"margin-top:0px;\">${res}</p></center>\n</div>\n</a>\n           "
   }
  },
  { "title": "Application Insights Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": {
    "content": "<h1 style=\"font-size: 20px; color:#73bf69;\"> Usage </h1>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "union\n    (traces\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (requests\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (pageViews\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (dependencies\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (customEvents\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (availabilityResults\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (exceptions\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (customMetrics\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (browserTimings\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo)\n| where notempty(user_Id)\n| summarize ['users/count_unique'] = dcount(user_Id) by bin(timestamp, 1m)\n| order by timestamp desc",
      "resource": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res",
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 5 },
   "options": {
    "content": "<h1 style=\"font-size:20px; color:#ec008c;\">Reliability</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "options": {
    "content": "<a href=\"/d/Azure-AppInsights-Failures-Operations?${am_ds:queryparam}&${sub:queryparam}&${rg:queryparam}&${ns:queryparam}&${res:queryparam}\" target=\"_blank\">\n<div>\n  <p style=\"font-size:16px; margin-bottom:0px; margin-top:0px;\"> Failures </p>\n  <p style=\"margin-top: 0px;\">${res}</p>\n</div>\n</a>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "options": {
    "content": "<h1 style=\"font-size:20px; color:#7e58ff;\">Responsiveness</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "options": {
    "content": "<a href=\"/d/Azure-AppInsights-Perf-Operations?${am_ds:queryparam}&${sub:queryparam}&${rg:queryparam}&${ns:queryparam}&${res:queryparam}\" target=\"_blank\">\n<div>\n  <p style=\"font-size:16px; margin-bottom:0px;margin-top:0px;\"> Performance </p>\n  <p style=\"margin-top:0px;\">${res}</p>\n</div>\n</a>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 5 },
   "options": {
    "content": "<h1 style=\"font-size:20px; color:#3274d9;\">Browser</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 5 },
   "options": {
    "content": "<a style=\"color: #ffffff;\" href=\"https://portal.azure.com/#blade/Microsoft_Azure_MonitoringMetrics/Metrics.ReactView/ResourceId/%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}/id/%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}/detailBlade/MetricsExplorerBlade/sourceExtension/AppInsightsExtension/TimeContext/%7B%22relative%22%3A%7B%22duration%22%3A86400000%7D%2C%22grain%22%3A1%2C%22options%22%3A%7B%22grain%22%3A1%2C%22showUTCTime%22%3Afalse%7D%7D/Chart/%7B%22v2charts%22%3A%5B%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22pageViews%2Fduration%22%2C%22color%22%3A%22msportalfx-bgcolor-g2%22%7D%2C%22name%22%3A%22pageViews%2Fduration%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A4%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A2%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3A%22operation%2Fname%22%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22Browsers%22%2C%22timespan%22%3A%7B%22relative%22%3A%7B%22duration%22%3A86400000%7D%2C%22grain%22%3A1%2C%22options%22%3A%7B%22grain%22%3A1%2C%22showUTCTime%22%3Afalse%7D%7D%7D%2C%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22dependencies%2Fduration%22%2C%22color%22%3A%22msportalfx-bgcolor-g2%22%7D%2C%22name%22%3A%22dependencies%2Fduration%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A4%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A2%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3A%22dependency%2Fname%22%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22Have%20AJAX%20calls%20been%20slow%3F%22%2C%22timespan%22%3A%7B%22relative%22%3A%7B%22duration%22%3A86400000%7D%2C%22grain%22%3A1%2C%22options%22%3A%7B%22grain%22%3A1%2C%22showUTCTime%22%3Afalse%7D%7D%7D%2C%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22pageViews%2Fcount%22%2C%22color%22%3A%22msportalfx-bgcolor-g2%22%7D%2C%22name%22%3A%22pageViews%2Fcount%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A1%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A2%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3A%22operation%2Fname%22%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22Has%20page%20view%20traffic%20changed%3F%22%2C%22timespan%22%3A%7B%22relative%22%3A%7B%22duration%22%3A86400000%7D%2C%22grain%22%3A1%2C%22options%22%3A%7B%22grain%22%3A1%2C%22showUTCTime%22%3Afalse%7D%7D%7D%2C%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22exceptions%2Fbrowser%22%2C%22color%22%3A%22msportalfx-bgcolor-g2%22%7D%2C%22name%22%3A%22exceptions%2Fbrowser%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A1%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A2%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3A%22exception%2FproblemId%22%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22When%20are%20script%20errors%20occurring%3F%22%2C%22timespan%22%3A%7B%22relative%22%3A%7B%22duration%22%3A86400000%7D%2C%22grain%22%3A1%2C%22options%22%3A%7B%22grain%22%3A1%2C%22showUTCTime%22%3Afalse%7D%7D%7D%2C%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22pageViews%2Fduration%22%2C%22color%22%3A%22msportalfx-bgcolor-g0%22%7D%2C%22name%22%3A%22pageViews%2Fduration%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A4%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A5%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3Afalse%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22What%20are%20my%20slowest%20pages%3F%22%7D%2C%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22pageViews%2Fduration%22%7D%2C%22name%22%3A%22pageViews%2Fduration%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A4%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A5%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3Afalse%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22What%20are%20my%20slowest%20pages%3F%22%7D%2C%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22exceptions%2Fbrowser%22%2C%22color%22%3A%22msportalfx-bgcolor-d0%22%7D%2C%22name%22%3A%22exceptions%2Fbrowser%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A1%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A5%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3A%22exception%2FproblemId%22%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22What%20are%20my%20most%20common%20script%20errors%3F%22%2C%22timespan%22%3A%7B%22relative%22%3A%7B%22duration%22%3A86400000%7D%2C%22grain%22%3A1%2C%22options%22%3A%7B%22grain%22%3A1%2C%22showUTCTime%22%3Afalse%7D%7D%7D%5D%7D/openInEditMode/\" target=\"_blank\">\n<div style=\"padding-top: 35px; background-color: #3274d9; width: 100%; height: 100%\">\n  <center><p style=\"font-size:16px; margin-bottom:0px;\"> Browsers </p></center>\n</div>\n</a>"
   }
  },
  {
   "title": "Users",
   "type": "timeseries",
   "description": "The resource path for this panel uses multiple template variables which requires modifying the dashboard JSON directly. If you would like to do something similar please go to Settings > JSON Model. Edit as you'd like in your new copy by going to Settings > Save as.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "union\n    (traces\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (requests\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (pageViews\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (dependencies\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (customEvents\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (availabilityResults\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (exceptions\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (customMetrics\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\n    (browserTimings\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo)\n| where notempty(user_Id)\n| summarize ['users/count_unique'] = dcount(user_Id) by bin(timestamp, $__interval)\n| order by timestamp desc",
      "resource": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res",
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    },
    {
     "azureLogAnalytics": {
      "query": "union\r\n    (traces\r\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\r\n    (requests\r\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\r\n    (pageViews\r\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\r\n    (dependencies\r\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\r\n    (customEvents\r\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\r\n    (availabilityResults\r\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\r\n    (exceptions\r\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\r\n    (customMetrics\r\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo),\r\n    (browserTimings\r\n    | where timestamp >= $__timeFrom and timestamp < $__timeTo)\r\n| where notempty(session_Id)\r\n| summarize ['sessions/count_unique'] = dcount(session_Id) by bin(timestamp, $__interval)\r\n| order by timestamp desc",
      "resource": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res",
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Server response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/duration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/microsoft.insights/components/$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Page Views",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "pageViews/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Average availability",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "availabilityResults/availabilityPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Server exceptions and Dependency failures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "exceptions/server",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "alias": "Dependency failures",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Average processor and process CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "performanceCounters/processorCpuPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "performanceCounters/processCpuPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Average page load time breakdown",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "browserTimings/networkDuration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "browserTimings/processingDuration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "browserTimings/sendDuration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "browserTimings/receiveDuration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Availability test results count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "availabilityResults/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Average process I/O rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "performanceCounters/processIOBytesPerSecond",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "100"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Average available memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "performanceCounters/memoryAvailableBytes",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Browser exceptions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "exceptions/browser",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}