{
 "title": "Azure / Insights / Applications / OTel / RPC AKS",
 "description": "Azure Monitor Application Insights with OpenTelemetry Metrics (RPC) on **Azure Kubernetes Service (AKS)**\r\n\r\nThis dashboard requires OpenTelemetry metrics to be ingested into an Application Insights resource with OTLP enabled.",
 "tags": [ "Azure-managed" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prom_ds", "label": "Data Source", "query": "prometheus" },
   {
    "name": "service_name",
    "query": {
     "query": "label_values({\"rpc.server.duration\"},k8s.deployment.name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "### Azure Monitor Application Insights with OpenTelemetry Metrics (RPC) on **Azure Kubernetes Service (AKS)**\n\nThis dashboard requires OpenTelemetry metrics to be ingested into an Application Insights resource with OTLP enabled.\nFor onboarding instructions, see [App Insights with OTel](https://aka.ms/AppInsightswithOTel)\n\n*Note: This dashboard should only be used for metrics which are ingested in cumulative temporality, the default setting for the Application Insights OpenTelemetry distro. [Learn More](https://aka.ms/OtelMetricTemp)*"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Server Requests Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "histogram_count(sum by (\"k8s.deployment.name\",) (increase({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__range])))",
     "legendFormat": "{{k8s.deployment.name}}"
    }
   ]
  },
  {
   "title": "Server Requests over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "histogram_count(sum by (\"k8s.deployment.name\") (increase({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) ",
     "legendFormat": "{{k8s.deployment.name}}"
    }
   ]
  },
  {
   "title": "Server Requests Total by Method",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "histogram_count(sum by (\"k8s.deployment.name\", \"rpc.method\") (increase({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__range]))) ",
     "legendFormat": "{{k8s.deployment.name}} / {{rpc.method}}"
    }
   ]
  },
  {
   "title": "Server Requests Total by Response Code",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "histogram_count(sum by (\"k8s.deployment.name\", \"rpc.grpc.status_code\") (increase({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__range]))) ",
     "legendFormat": "{{k8s.deployment.name}} - {{rpc.grpc.status_code}}"
    }
   ]
  },
  {
   "title": "Server Requests Total by Route",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "histogram_count(sum by (\"k8s.deployment.name\", \"rpc.system\") (increase({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__range]))) ",
     "legendFormat": "{{k8s.deployment.name}} -  {{rpc.system}} "
    }
   ]
  },
  { "title": "Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Failed Server Requests Total by Method and Response Code",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "histogram_count(sum by(\"k8s.deployment.name\", \"rpc.method\", \"rpc.grpc.status_code\") (increase({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\", \"rpc.grpc.status_code\"!=\"0\"}[$__range]))) ",
     "legendFormat": "{{k8s.deployment.name}} - {{rpc.method}} - {{rpc.grpc.status_code}}"
    }
   ]
  },
  {
   "title": "Failed Server Requests Total by Method and Response Code",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 22 },
   "targets": [
    {
     "expr": "histogram_count(sum by(\"k8s.deployment.name\", \"rpc.method\", \"rpc.grpc.status_code\") (increase({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\", \"rpc.grpc.status_code\"!=\"0\"}[$__rate_interval]))) ",
     "legendFormat": "{{k8s.deployment.name}} - {{rpc.method}} - {{rpc.grpc.status_code}}"
    }
   ]
  },
  {
   "title": "Failed Client Requests Total by Method and Response Code",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "histogram_count(sum by( \"k8s.deployment.name\", \"rpc.method\", \"rpc.grpc.status_code\") (increase({\"rpc.client.duration\", \"k8s.deployment.name\"=~\"$service_name\", \"rpc.grpc.status_code\"!=\"0\"}[$__range]))) ",
     "legendFormat": "{{k8s.deployment.name}} - {{rpc.method}} - {{rpc.grpc.status_code}}"
    },
    {
     "expr": "histogram_count(sum by(\"k8s.deployment.name\", \"http.status_code\") (increase({\"http.client.duration\", \"k8s.deployment.name\"=~\"$service_name\", \"http.status_code\"=~\"5..|4..\"}[$__range]))) or (histogram_count(sum by(le, \"k8s.deployment.name\", \"http.status_code\") (increase({\"http.client.request.duration\", \"k8s.deployment.name\"=~\"$service_name\", \"http.status_code\"=~\"5..$..\"}[$__range]))))",
     "legendFormat": "{{k8s.deployment.name}} - {{http.status_code}}"
    }
   ]
  },
  {
   "title": "Failed Client Requests Total by Method and Response Code",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 27 },
   "targets": [
    {
     "expr": "histogram_count(sum by(\"k8s.deployment.name\", \"rpc.method\", \"rpc.grpc.status_code\") (increase({\"rpc.client.duration\", \"k8s.deployment.name\"=~\"$service_name\", \"rpc.grpc.status_code\"!=\"0\"}[$__rate_interval]))) ",
     "legendFormat": "{{k8s.deployment.name}} - {{rpc.method}} - {{rpc.grpc.status_code}}"
    },
    {
     "expr": "histogram_count(sum by( \"k8s.deployment.name\", \"http.status_code\") (increase({\"http.client.duration\", \"k8s.deployment.name\"=~\"$service_name\", \"http.status_code\"=~\"5..|4..\"}[$__rate_interval]))) or (histogram_count(sum by(\"k8s.deployment.name\", \"http.status_code\") (increase({\"http.client.request.duration\", \"k8s.deployment.name\"=~\"$service_name\", \"http.status_code\"=~\"5..$..\"}[$__rate_interval]))))",
     "legendFormat": "{{k8s.deployment.name}} - {{http.status_code}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Average Server Response Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "histogram_avg(sum by (\"k8s.deployment.name\") (increase({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) ",
     "legendFormat": "{{k8s.deployment.name}}"
    }
   ]
  },
  {
   "title": "Average Server Response Time by Method (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "histogram_avg(sum by (\"k8s.deployment.name\",\"rpc.method\") (increase({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) ",
     "legendFormat": "{{k8s.deployment.name}} / {{rpc.method}}"
    }
   ]
  },
  {
   "title": "95th Percentile Server Response Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (\"k8s.deployment.name\", le) (rate({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) ",
     "legendFormat": "{{k8s.deployment.name}}"
    }
   ]
  },
  {
   "title": "95th Percentile Server Response Time by Method (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (\"k8s.deployment.name\", \"rpc.method\", le) (rate({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) ",
     "legendFormat": "{{k8s.deployment.name}} / {{rpc.method}}"
    }
   ]
  },
  {
   "title": "Average Server Request Rate (r/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "histogram_count(sum by (\"k8s.deployment.name\") (rate({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) ",
     "legendFormat": "{{k8s.deployment.name}}"
    }
   ]
  },
  {
   "title": "Average Server Request Rate by Method (r/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "histogram_count(sum by (\"k8s.deployment.name\", \"rpc.method\") (rate({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "{{k8s.deployment.name}} / {{rpc.method}}"
    }
   ]
  },
  {
   "title": "Average Server Response Time  (seconds)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_avg(sum by (\"k8s.deployment.name\") (increase({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "{{k8s.deployment.name}} "
    }
   ]
  },
  {
   "title": "Average Server Response Time by Method (seconds)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_avg(sum by (\"k8s.deployment.name\",\"rpc.method\") (increase({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) ",
     "legendFormat": "{{k8s.deployment.name}} / {{rpc.method}}"
    }
   ]
  },
  { "title": "Dependencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Average Client Response Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "histogram_avg(sum by (\"k8s.deployment.name\") (increase({\"rpc.client.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) ",
     "legendFormat": "{{k8s.deployment.name}}"
    },
    {
     "expr": "histogram_avg(sum by (\"k8s.deployment.name\") (increase({\"http.client.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) or histogram_avg(sum by (\"k8s.deployment.name\") (increase({\"http.client.request.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "{{servic.name}}"
    }
   ]
  },
  {
   "title": "Average Client Response Time by RPC Method and HTTP Route (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "histogram_avg(sum by (\"k8s.deployment.name\",\"rpc.method\") (increase({\"rpc.client.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) ",
     "legendFormat": "{{k8s.deployment.name}} / {{rpc.method}}"
    },
    {
     "expr": "histogram_avg(sum by (\"k8s.deployment.name\",\"http.route\") (increase({\"http.client.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) or histogram_avg(sum by (\"k8s.deployment.name\",\"http.route\") (increase({\"http.client.request.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "{{k8s.deployment.name}} {{http.route}}"
    }
   ]
  },
  {
   "title": "95th Percentile - Client Response Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (\"k8s.deployment.name\", le) (rate({\"rpc.client.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "{{k8s.deployment.name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (\"k8s.deployment.name\", le) (rate({\"http.client.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) or histogram_quantile(0.95, sum by (\"k8s.deployment.name\", le) (rate({\"http.client.request.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "{{k8s.deployment.name}}"
    }
   ]
  },
  {
   "title": "95th Percentile - Client Response Time by RPC Method and HTTP Route (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (\"k8s.deployment.name\",\"rpc.method\", le) (rate({\"rpc.client.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) ",
     "legendFormat": "{{k8s.deployment.name}} {{rpc.method}} "
    },
    {
     "expr": "histogram_quantile(0.95, sum by (\"k8s.deployment.name\",\"http.route\", le) (rate({\"http.client.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) or histogram_quantile(0.95, sum by (\"k8s.deployment.name\",\"http.route\", le) (rate({\"http.client.request.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "{{k8s.deployment.name}} {{http.route}}"
    }
   ]
  },
  { "title": "Table View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Average Server Response Time (seconds)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_avg(sum by (\"k8s.deployment.name\", \"rpc.method\") (increase({\"rpc.server.duration\", \"k8s.deployment.name\"=~\"$service_name\"}[$__rate_interval]))) ",
     "legendFormat": "{{k8s.deployment.name}} {{rpc.method}}"
    }
   ]
  }
 ]
}