resources:
  - otelapidemo-dotnet.yaml
  - otelapidemo-python.yaml
  - otelapidemo-cpp.yaml
  - otel-ui.yaml
  - otelapidemo-ingress.prod.yaml
  - otel-ui-ingress.prod.yaml
  - otel-ui-otlp-service.yaml
  - otel-ui-otlp-ingress.prod.yaml