apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-auto-prod
  namespace: observability
  annotations:
    otel.config/version: "v1.0.1"
    otel.config/updated: "2026-07-03"
spec:
  exporter:
    endpoint: http://otel-agent-opentelemetry-collector.observability.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "0.1"
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: grpc
      - name: OTEL_TRACES_SAMPLER
        value: parentbased_traceidratio
      - name: OTEL_TRACES_SAMPLER_ARG
        value: "0.1"
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: "true"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: deployment.environment.name=prod
